### ISSUE TITLE
ERROR Error: Uncaught (in promise): [object Undefined]

### ISSUE THREAD

**Issue by med-amin** [WarriorRocker/angular-xo-material#4]
When i try to load the page with this theme, the page remains blank and i get this error in console 

`ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)`

**Comment by WarriorRocker** [comment]
Can you check that your App Config entrypoint is added to your src index.html?

https://angularxo.io/guides/angular#adding-appconfig

Make sure to compile the theme using `npm run build` or `npm run deploy`.

Also verify that the Xo API is functioning, for example: https://angularxo.io/xo-api/config

 Replace the domain with your own in the above.

**Comment by med-amin999** [comment]
I checked the page in WordPress admin and this problem happens only in the content page, the home page and sitemap works fine  i included images from the xo api and the index page 
![xo-config](https://user-images.githubusercontent.com/46812464/55459143-be984500-55e6-11e9-8d62-bc43c708d0e0.png)
![xoapi](https://user-images.githubusercontent.com/46812464/55459145-bf30db80-55e6-11e9-820d-c0896ed13372.png)

**Comment by WarriorRocker** [comment]
Are you using ACF Pro? The content template is built using ACF fields with flexible layout and repeaters. The default template only uses the WordPress default editor, either MCE or Gutenberg depending on your WordPress version and settings.

Additionally the content page also generates the contents sidebar nav using these ACF fields, likely there needs to be additional conditions for when that code is used which is probably the reason for your error above.

I will look into this further.

**Comment by med-amin** [comment]
I already installed ACF and ACF PRO and activated them,
![acf](https://user-images.githubusercontent.com/46812464/55476155-b99abc00-560d-11e9-8e1b-06edadbcc8a8.png)

**Comment by WarriorRocker** [comment]
Checking to see if the above has been resolved based on the other issue https://github.com/WarriorRocker/angular-xo-material/issues/5

**Comment by med-amin** [comment]
@WarriorRocker  The other issue #5 problems is resolved but the problem in this issue #4   is that we can't use the "content" template  in the Front page as a template but you can use'it in any other page that is not a front page

**Comment by WarriorRocker** [comment]
After some investigation it appears that the API call for the breadcrumbs was failing for the home page, as it should as the home page should have no parents. Since the home template does not use these breadcrumbs it was not a problem I had previously seen.

To address this an updated angular-xo module has been pushed which does not reject a route resolve promise when the request for breadcrumbs fails. This request is non-critical and should not stop normal processing of the page.

Additionally an update to the angular-xo-material theme has been pushed that adds an *ngIf to pages which use the breadcrumbs component to only display if there are breadcrumbs to show. Otherwise on the content template there would be the breadcrumbs bar with only a home icon, redundant if you are already on the home page.

Pull latest for the theme and run a build or deploy. Let me know if this still gives you an issue.
