### ISSUE TITLE
Is there a way to override route to show angular component instead of wp page contents?

### ISSUE THREAD

**Issue by gsse7en** [WarriorRocker/angular-xo-material#8]
Lets say I have a wp page with route `/about` and I want angular to serve its own component that lives inside `/about` route, how can I achieve that? All other wp pages should be fetched to angular with the Plugin.
Tried adding route to Xo lazy loaded routes, but it still fetches wp page.
Created angular component `<test-component></test-component>` and added this tag to wp page contents, but wp strips unknown tags.

**Comment by WarriorRocker** [comment]
Currently when using the [XoRoutesService ](https://angularxo.io/guides/angular#integrate-xorouteservice-from-angular-xo) the routes defined in [app.routing.ts](https://angularxo.io/guides/angular#enable-lazy-loaded-routes) are replaced with those from the [Xo API Routes Controller](https://angularxo.io/api/controllers/routes#routes-get).

What you could do is setup a new page template module "about.module.ts" with [template annotations](https://angularxo.io/guides/templates) so that the template is seen by WordPress.

Then define your module like the other template modules excluding the [XoPostResolver](https://angularxo.io/guides/routing#adding-xopostresolver) service.

```
/**
 * @XoPageTemplate About
 * @XoLoadChildren MyNonResolvedPageModule
 * @XoDisableEditor True
 */

@NgModule({
  imports: [
    ...,
    RouterModule.forChild([
      {
        path: '',
        component: MyNonResolvedPageComponent
      }
    ])
  ],
  declarations: [MyNonResolvedPageComponent]
})
export class MyNonResolvedPageModule { }
```

Now you should be able to create a new page with title "About" and URL "/about" with this page template selected. This will instruct both WordPress and your Angular app that this URL exists but won't request the data for this page from the WordPress.

Make sure to add a new "fake" route for this page module in your app.module.ts otherwise the Angular CLI won't include the new module in builds.

**Comment by gsse7en** [comment]
I've added about.module:
`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { MatButtonModule, MatIconModule } from '@angular/material';

import { AboutPageComponent } from './about.component';
import { XoMaterialSectionsModule } from '../../components/sections/sections.module';

/**
 * @XoPageTemplate About
 * @XoLoadChildren AboutPageModule
 * @XoDisableEditor True
 */

@NgModule({
	imports: [
		CommonModule,
		MatButtonModule,
		MatIconModule,
		XoMaterialSectionsModule,
		RouterModule.forChild([
			{
				path: '',
				component: AboutPageComponent,
			}
		])
	],
	declarations: [AboutPageComponent]
})
export class AboutPageModule { }
`
(Also tried adding Templates annotations to the top)
Added route to app.routing:
`import { Routes } from '@angular/router';

export const XoMaterialAppLazyRoutes: Routes = [
	{
		path: 'xo-material-page-default',
		loadChildren: './pages/default/default.module#XoMaterialDefaultPageModule',
	},
	{
		path: 'xo-material-page-home',
		loadChildren: './pages/home/home.module#XoMaterialHomePageModule',
	},
	{
		path: 'xo-material-page-content',
		loadChildren: './pages/content/content.module#XoMaterialContentPageModule',
	},
	{
		path: 'xo-material-page-posts',
		loadChildren: './pages/posts/posts.module#XoMaterialPostsPageModule',
	},
	{
		path: 'xo-material-page-sitemap',
		loadChildren: './pages/sitemap/sitemap.module#XoMaterialSitemapPageModule',
	},
	{
		path: 'about',
		loadChildren: './pages/about/about.module#AboutPageModule',
	}
];
`
Still '/about' route serves me wp page contents.
Only if I set the WP Plugin Settings -> Templates Reader -> Reader Enabled to false - I can see my angular component contents, but then I can't access routers fetched from wp.

**Comment by WarriorRocker** [comment]
Did you create a new page in your WordPress admin with this template selected?

The annotations only make the template available for use within WordPress. The routes configured at the root of your Angular App "app.routing.ts" will be completely replaced by those from the API. Even if you won't use WordPress to manage the content of your About page, go ahead and create it as a page with your About template selected. This way Xo knows to include the route(s) in your theme, without the XoPostResolver set the module/component won't request any further data for this page from your WordPress.

The lazy routes path should be something unique enough that it never conflicts with the real routes.

```
export const XoMaterialAppLazyRoutes: Routes = [
	...,
	{
		path: 'my-about-page-template',
		loadChildren: './pages/about/about.module#AboutPageModule',
	}
];
```

Can you make sure the route is output in the API: https://angularxo.io/xo-api/routes/get

**Comment by gsse7en** [comment]
Thank you very much for your answer!
The issue was that when I added routes in angular - I didn't change the template name for this pages in wp!
